spring.application.name=apartment-management-system
server.error.whitelabel.enabled=true

spring.datasource.url=jdbc:mysql://172.19.10.60:3306/apartment_db?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.mvc.favicon.enabled=false
server.error.whitelabel.enabled=false